SeguridadWebv2/Models/Aplicacion/Turno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SeguridadWebv2.Models.Aplicacion
{
    [Table("Turnos")]
    public class Turno
    {
        public Turno()
        {
            this.IdTurno = Guid.NewGuid().ToString();
            this.EstadoTurno = Estado.Reservado;
        }

        [Key]
        public string IdTurno { get; set; }
        public DateTime Dia { get; set; }
        public DateTime HoraInicio { get; set; }
        public DateTime HoraFin { get; set; }
        public Estado EstadoTurno { get; set; }
        public string RelacionId { get; set; }

        [ForeignKey("RelacionId")]
        public virtual Relacion RelacionPacienteEspecialista { get; set; }
    }

    public enum Estado
    {
        Reservado = 1,
        Cancelado = 2,
        Pendiente = 3,
        Confirmado = 4,
        Finalizado = 5,
        Rechazado = 6,
        Anulado = 7
    }
}

SeguridadWebv2/Models/ViewModels/TurnosViewModel.cs
using SeguridadWebv2.Models.Aplicacion;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SeguridadWebv2.Models.ViewModels
{
    public class TurnosViewModel
    {
        public string IdTurno { get; set; }
        public DateTime Dia { get; set; }
        public DateTime HoraInicio { get; set; }
        public DateTime HoraFin { get; set; }
        public Estado EstadoTurno { get; set; }
        public string RelacionId { get; set; }
        public decimal Precio { get; set; }
        public Especialista Especialista { get; set; }
        public Paciente Paciente { get; set; }

        public string FullNamePacienteTurno {
            get { return this.Paciente.Nombre + " " + this.Paciente.Apellido; }
        }

        public string FullNameEspecialistaTurno
        {
            get { return this.Especialista.Nombre + " " + this.Especialista.Apellido; }
        }

    }
}

SeguridadWebv2/Controllers/TurnoController.cs
using Microsoft.AspNet.Identity;
using SeguridadWebv2.Models;
using SeguridadWebv2.Models.Aplicacion;
using SeguridadWebv2.Services;
using SeguridadWebv2.Validations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SeguridadWebv2.Controllers
{
    [Authorize]
    public class TurnoController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Turno
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult ReservarTurno(string id, string espec)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var showhorario = db.HorariosDisponibles.Where(x => x.Id == id).FirstOrDefault();
            var especialista = db.Especialistas.Where(x => x.Id == espec).FirstOrDefault();

            if (showhorario == null)
            {
                return HttpNotFound();
            }

            var tipotarjeta = from TipoTarjeta d in Enum.GetValues(typeof(TipoTarjeta))
                              select new { IdTipoTarjeta = (int)d, Name = d.ToString() };

            var mestarjeta = from Mes d in Enum.GetValues(typeof(Mes))
                              select new { IdMesTarjeta = (int)d, Name = (int)Enum.Parse(typeof(Mes), d.ToString()) };

            var anotarjeta = from AnoExpiracion d in Enum.GetValues(typeof(AnoExpiracion))
                             select new { IdAnoExp = (int)d, Name = (int)Enum.Parse(typeof(AnoExpiracion), d.ToString()) };



            ViewBag.IdTipoTarjeta = new SelectList(tipotarjeta, "IdTipoTarjeta", "Name");
            ViewBag.IdMesTarjeta = new SelectList(mestarjeta, "IdMesTarjeta", "Name");
            ViewBag.IdAnoExp = new SelectList(anotarjeta, "IdAnoExp", "Name");

            ViewBag.IdHorarioShowView = showhorario.Id;
            ViewBag.IdEspecislistaShowView = especialista.Id;

            var model = new TurnoReservaViewModel
            {
                TurnoViewModel = new TurnoViewModel
                {
                    Horario = db.HorariosDisponibles.Include("Horario").Single(x => x.Id == showhorario.Id),
                },
                TarjetaViewModel = new TarjetaViewModel()
            }; 
            return View(model);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ConfirmarPagoReserva(TurnoReservaViewModel model)
        {
            if (ModelState.IsValid)
            {
                string validartarjeta = TarjetaCreditoValidation.ValidateCardNumber(model.TarjetaViewModel.NumeroTarjeta);
                bool c = TarjetaCreditoValidation.IsValidCardType(TarjetaCreditoValidation.CleanCreditCardNumber(model.TarjetaViewModel.NumeroTarjeta));

                //TurnoReserva turnoreserva = new TurnoReserva();
                //turnoreserva.UserId = System.Web.HttpContext.Current.User.Identity.GetUserId();
                //turnoreserva.Estado = Estado.Reservado;

                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                Paciente paciente = db.Pacientes.ToList().FirstOrDefault(x => x.Id == currentUser.Id);
                
                var horarioDisponible = db.HorariosDisponibles.Include("Horario").FirstOrDefault(x => x.Id == model.TurnoViewModel.Horario.Id);
                //var horarioDisponible = _db.HorariosDisponibles.Where(x => x.Disponible == true).OrderBy(x => x.Dia).Include(h => h.Horario).Include(e => e.Horario.Especialista).FirstOrDefault(x => x.Id == HorarioDisponible.Id); //.Find(Id);

                Relacion relacion = new Relacion();
                bool existeRelacion = false;
                foreach (Relacion relaciones in db.RelacionPacienteEspecialista.Include("Paciente").Include("Especialista"))
                {
                    if (relaciones.Especialista.EspecialidadId == horarioDisponible.Horario.EspecialistaId && relaciones.Paciente.Id == paciente.Id)
                    {
                        existeRelacion = true;
                        relacion = relaciones;
                    }
                }

                if (existeRelacion != true)
                {
                    relacion.Especialista = horarioDisponible.Horario.Especialista;
                    relacion.Paciente = paciente;

                    Turno turno = new Turno();
                    turno.Dia = horarioDisponible.Dia;
                    turno.HoraInicio = horarioDisponible.HoraInicio;
                    turno.HoraFin = horarioDisponible.HoraFin;
                    turno.RelacionPacienteEspecialista = relacion;
                    turno.EstadoTurno = Estado.Pendiente;
                    relacion.Turnos.Add(turno);
                    horarioDisponible.Disponible = EstadoHorario.Ocupado;
                    relacion.FechaRelacion = DateTime.Now;
                    db.RelacionPacienteEspecialista.Add(relacion);
                    db.SaveChanges();
                    return RedirectToAction("Dashboard", "Home");
                }
                else
                {
                    var turno = new Turno();

                    turno.Dia = horarioDisponible.Dia;
                    turno.HoraInicio = horarioDisponible.HoraInicio;
                    turno.HoraFin = horarioDisponible.HoraFin;
                    turno.RelacionPacienteEspecialista = relacion;
                    turno.EstadoTurno = Estado.Pendiente;
                    relacion.Turnos.Add(turno);
                    horarioDisponible.Disponible = EstadoHorario.Disponible;
                    db.SaveChanges();
                    return RedirectToAction("Dashboard", "Home");
                }
            }
            return View(model);
        }
    }
}

SeguridadWebv2/Views/Turno/ReservarTurno.cshtml
@model SeguridadWebv2.Models.Aplicacion.TurnoReservaViewModel

<h2>ReservarTurno</h2>

<div class="row">
        @using (Html.BeginForm("ConfirmarPagoReserva", "Turno", FormMethod.Post))
        {
            <div class="col-md-12">
                <div class="col-md-8">
                    <!--FORM TARJETA DE CREDITO-->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><img class="pull-right" src="~/Content/img/tarjetas_aceptadas.png">Forma y Detalles de Pago</h3>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="control-label col-md-3"><strong>Tipo Tarjeta</strong></div>
                                <div class="col-md-8 input-group">
                                    @Html.DropDownList("IdTipoTarjeta", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TarjetaViewModel.IdTipoTarjeta, "", new { @class = "text-danger" })
                                    <span class="input-group-addon">
                                        <span class="fa fa-credit-card">
                                        </span>
                                    </span>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="control-label col-md-3"><strong>Numero de Tarjeta</strong></div>
                                <div class="col-md-8 input-group">
                                    @Html.TextBoxFor(model => model.TarjetaViewModel.NumeroTarjeta, new { @class = "form-control", placeholder = "Ingrese los 16 digitos de su tarjeta" })
                                    @Html.ValidationMessageFor(model => model.TarjetaViewModel.NumeroTarjeta, "", new { @class = "text-danger" })
                                    <span class="input-group-addon">
                                        <span class="fa fa-credit-card">
                                        </span>
                                    </span>
                                </div>
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="col-md-4 col-sm-3 col-xs-3">
                                    <div class="control-label"><strong> Mes de Expiración</strong></div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            @Html.DropDownList("IdMesTarjeta", (SelectList)ViewBag.IdMesTarjeta, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TarjetaViewModel.IdMesTarjeta, "", new { @class = "text-danger" })
                                            <span class="input-group-addon">
                                                <span class="fa fa-calendar-plus-o">
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4 col-sm-3 col-xs-3">
                                    <div class="control-label"><strong>Año de Expiración</strong></div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            @Html.DropDownList("IdAnoExp", (SelectList)ViewBag.IdAnoExp, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TarjetaViewModel.IdAnoExp, "", new { @class = "text-danger" })
                                            <span class="input-group-addon">
                                                <span class="fa fa-calendar-minus-o">
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-4 col-sm-3 col-xs-3">
                                    <div class="control-label"><strong>CVV de Seguridad</strong></div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            @Html.PasswordFor(model => model.TarjetaViewModel.CodigoSeguridad, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.TarjetaViewModel.CodigoSeguridad, "", new { @class = "text-danger" })
                                            <span class="input-group-addon">
                                                <span class="fa fa-credit-card-alt">
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="col-md-6 col-sm-6 col-xs-3">
                                    <div class="control-label"><strong>Nombre Del Titular Tarjeta</strong></div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.TarjetaViewModel.NombreClienteTarjeta, new { @class = "form-control", placeholder = "Nombre Titular de la Tarjeta" })
                                            @Html.ValidationMessageFor(model => model.TarjetaViewModel.NombreClienteTarjeta, "", new { @class = "text-danger" })
                                            <span class="input-group-addon">
                                                <span class="fa fa-user">
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6 col-sm-6 col-xs-3">
                                    <div class="control-label"><strong>DNI Titular</strong></div>
                                    <div class="form-group">
                                        <div class="input-group">
                                            @Html.TextBoxFor(model => model.TarjetaViewModel.DNIClienteTarjeta, new { @class = "form-control", placeholder = "DNI Titular de la Tarjeta" })
                                            @Html.ValidationMessageFor(model => model.TarjetaViewModel.DNIClienteTarjeta, "", new { @class = "text-danger" })
                                            <span class="input-group-addon">
                                                <span class="fa fa-tags">
                                                </span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="panel panel-danger">
                        <div class="panel-body">
                            <div class="col-md-3">
                                <img src="@Url.Content(@Model.TurnoViewModel.Horario.Horario.Especialista.ImagenMedico)" class="img-circle img-responsive" />
                            </div>
                            <div class="col-md-9">
                                <div class="header">
                                    @Html.HiddenFor(x => x.TurnoViewModel.Horario.Id, new { @class = "idesp" })
                                    @Model.TurnoViewModel.Horario.Horario.Especialista.Prefijo @Model.TurnoViewModel.Horario.Horario.Especialista.Nombre @Model.TurnoViewModel.Horario.Horario.Especialista.Apellido
                                    @Model.TurnoViewModel.Horario.Horario.Especialista.PhoneNumber
                                    @Model.TurnoViewModel.Horario.Horario.Especialista.NumeroMatricula
                                </div>
                                <div class="jumbotron">
                                    @Model.TurnoViewModel.Horario.Horario.Dia.ToString()
                                    @Model.TurnoViewModel.Horario.HoraInicio.ToString()
                                    @Model.TurnoViewModel.Horario.HoraFin.ToString()
                                    @Model.TurnoViewModel.Horario.Precio
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12 col-sm-6 col-xs-6 pad-adjust">
                    <input type="submit" class="btn btn-warning btn-block" value="PAGAR" />
                </div>
            </div>
        }
</div>

@section Scripts {
   @Scripts.Render("~/bundles/jqueryval")
}