SeguridadWebv2/Controllers/EspecialistaController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SeguridadWebv2.Models;
using SeguridadWebv2.Models.Aplicacion;
using SeguridadWebv2.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SeguridadWebv2.Controllers
{
    public class EspecialistaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        public EspecialistaController()
        {
        }

        public EspecialistaController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Especialista
        public ActionResult Index()
        {
            return View();
        }
        
        private ApplicationSignInManager _signInManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set { _signInManager = value; }
        }

        
        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult Registrarse()
        {
            RegistrarseEspViewModel registrarse = new RegistrarseEspViewModel();
            ViewBag.Especialidades = db.Especialidades.ToList(); 
            return View(registrarse);
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Registrarse(RegistrarseEspViewModel model)
        {
            model.Estado = true;
            if (ModelState.IsValid)
            {
                var especialidad = db.Especialidades.Find(model.IdEspecialidad);
                if (especialidad == null)
                {
                    return HttpNotFound();
                }
                string pathimage = "~/Content/img/doctor.png"; 
                Especialista user = new Especialista { UserName = model.Email, Email = model.Email, Nombre = model.Nombre, Apellido = model.Apellido, Estado = model.Estado, PhoneNumber = model.Telefono, NumeroMatricula = model.Matricula, EspecialidadId = model.IdEspecialidad, ImagenMedico = pathimage };
                var result = await UserManager.CreateAsync(user, model.Password);
                GrupoManager groupManager = new GrupoManager();
                var group = db.ApplicationGroups.Where(x => x.Name == "Especialistas").FirstOrDefault();
                groupManager.SetUserGroups(user.Id, group.Id);
                if (result.Succeeded)
                {
                    //await this.groupManager.SetUserGroups(user.Id, "Profesionales");
                    var code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    var callbackUrl = Url.Action("ConfirmarEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    await UserManager.SendEmailAsync(user.Id, "Confirmar su cuenta", "Por favor para confirmar su cuenta haga click en el siguiente enlace: <a href=\"" + callbackUrl + "\">link</a>");

                    //ViewBag.Link = callbackUrl;
                    return View("DisplayEmail");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Turnos(string id, DateTime? dato)
        {
            if (dato == null)
            {
                DateTime date = Convert.ToDateTime(DateTime.Now);
            }
            Especialista espec = db.Especialistas.FirstOrDefault(x => x.Id == id);
            
            IEnumerable<HorarioDisponible> horariodisponible = (from horariosdisp in db.HorariosDisponibles
                                                    join horarios in db.Horarios on horariosdisp.HorarioId equals horarios.IDHorario
                                                    join especi in db.Especialistas on horarios.EspecialistaId equals especi.Id
                                                    where horarios.EspecialistaId == id && horariosdisp.Disponible == EstadoHorario.Disponible
                                                    select horariosdisp).ToList();

            var model = new GeneralViewModels
            {
                Especialista = espec,
                Horarios = horariodisponible.ToList()
            };
            return View(model);
        }


        //[HttpGet]
        //public JsonResult SearchtoDateTurno(string id, DateTime dato)
        //{
        //    Especialista espec = db.Especialistas.FirstOrDefault(x => x.EspecialistaId == id);

        //    IQueryable<Horario> horario = db.Horarios.Where(x => x.Especialista.EspecialistaId == id &&
        //                                    DbFunctions.TruncateTime(x.FechaInicio) == DbFunctions.TruncateTime(dato))
        //                                    .OrderBy(x => x.FechaInicio)
        //                                    .Include(x => x.Especialista);
        //    var data = new GeneralViewModels
        //    {
        //        Especialista = espec,
        //        Horarios = horario.ToList()
        //    };

        //    return Json(data, JsonRequestBehavior.AllowGet);
        //}

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Home");
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

    }
}

SeguridadWebv2/Controllers/GruposAdminController.cs
using SeguridadWebv2.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SeguridadWebv2.Controllers
{
    [Authorize(Roles = "Admin, AllGrupos")]
    public class GruposAdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private GrupoManager _groupManager;
        public GrupoManager GroupManager
        {
            get
            {
                return _groupManager ?? new GrupoManager();
            }
            private set
            {
                _groupManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext()
                    .Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        public ActionResult Index()
        {
            return View(this.GroupManager.Groups.ToList());
        }


        public async Task<ActionResult> Detalles(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup =
                await this.GroupManager.Groups.FirstOrDefaultAsync(g => g.Id == id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }
            var groupRoles = this.GroupManager.GetGroupRoles(applicationgroup.Id);
            string[] RoleNames = groupRoles.Select(p => p.Name).ToArray();
            ViewBag.RolesList = RoleNames;
            ViewBag.RolesCount = RoleNames.Count();
            return View(applicationgroup);
        }


        public ActionResult Agregar()
        {
            //Get a SelectList of Roles to choose from in the View:
            ViewBag.RolesList = new SelectList(
                this.RoleManager.Roles.ToList(), "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Agregar(
            [Bind(Include = "Name,Description")] ApplicationGroup applicationgroup, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                // Create the new Group:
                var result = await this.GroupManager.CreateGroupAsync(applicationgroup);
                if (result.Succeeded)
                {
                    selectedRoles = selectedRoles ?? new string[] { };

                    // Add the roles selected:
                    await this.GroupManager.SetGroupRolesAsync(applicationgroup.Id, selectedRoles);
                }
                return RedirectToAction("Index");
            }

            // Otherwise, start over:
            ViewBag.RoleId = new SelectList(
                this.RoleManager.Roles.ToList(), "Id", "Name");
            return View(applicationgroup);
        }


        public async Task<ActionResult> Editar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }

            // Get a list, not a DbSet or queryable:
            var allRoles = await this.RoleManager.Roles.ToListAsync();
            var groupRoles = await this.GroupManager.GetGroupRolesAsync(id);

            var model = new GrupoViewModel()
            {
                Id = applicationgroup.Id,
                Name = applicationgroup.Name,
                Descripcion = applicationgroup.Description
            };

            // load the roles/Roles for selection in the form:
            foreach (var Role in allRoles)
            {
                var listItem = new SelectListItem()
                {
                    Text = Role.Name,
                    Value = Role.Id,
                    Selected = groupRoles.Any(g => g.Id == Role.Id)
                };
                model.RolesList.Add(listItem);
            }
            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar(
            [Bind(Include = "Id,Name,Description")] GrupoViewModel model, params string[] selectedRoles)
        {
            var group = await this.GroupManager.FindByIdAsync(model.Id);
            if (group == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                group.Name = model.Name;
                group.Description = model.Descripcion;
                await this.GroupManager.UpdateGroupAsync(group);

                selectedRoles = selectedRoles ?? new string[] { };
                await this.GroupManager.SetGroupRolesAsync(group.Id, selectedRoles);
                return RedirectToAction("Index");
            }
            return View(model);
        }


        public async Task<ActionResult> Eliminar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            if (applicationgroup == null)
            {
                return HttpNotFound();
            }
            return View(applicationgroup);
        }


        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmarEliminar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationgroup = await this.GroupManager.FindByIdAsync(id);
            await this.GroupManager.DeleteGroupAsync(id);
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SeguridadWebv2/Views/Shared/_DashboardIzquierdo.cshtml
<div id="sidebar" class="nav-collapse">
    <!-- sidebar menu start-->
    <ul class="sidebar-menu" id="nav-accordion">
        <p class="centered"><a href="profile.html"><img src="assets/img/ui-sam.jpg" class="img-circle" width="60"></a></p>
        <h5 class="centered">@User.Identity.Name</h5>

        @if (Request.IsAuthenticated && User.IsInRole("Admin")) { 
        <li class="sub-menu">
            <a class="active" href="javascript:;">
                <i class="fa fa-dashboard"></i>
                <span>Seguridad</span>
            </a>
            <ul class="sub">
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("AllUsuarios"))
                {
                    <li>@Html.ActionLink("Usuarios", "Index", "UsuariosAdmin")</li>
                }
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("AllGrupos"))
                {
                    <li>@Html.ActionLink("Grupos", "Index", "GruposAdmin")</li>
                }
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("AllPermisos"))
                {
                    <li>@Html.ActionLink("Acciones", "Index", "AccionesAdmin")</li>
                }
            </ul>
        </li>
        }
        <li class="sub-menu">
            <a href="javascript:;">
                <i class="fa fa-suitcase" ></i>
                <span>Turnos</span>
            </a>
            <ul class="sub">
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("AllAutos"))
                {
                    <li>@Html.ActionLink("Gestion de Turnos", "Index", "Turnos")</li>
                }
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Reportes"))
                {
                    <li>@Html.ActionLink("Gestion de Reportes", "Reportes", "Turnos")</li>
                }
            </ul>
        </li>
        <li class="sub-menu">
            <a href="javascript:;">
                <i class=" fa fa-bar-chart-o"></i>
                <span>Especialistas</span>
            </a>
            <ul class="sub">
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Reportes"))
                {
                    <li>@Html.ActionLink("Gestion de Especialistas", "Index", "Especialista")</li>
                    <li>@Html.ActionLink("Gestion de Reportes", "Reportes", "Especialista")</li>
                }
            </ul>
        </li>

        <li class="sub-menu">
            <a href="javascript:;">
                <i class=" fa fa-bar-chart-o"></i>
                <span>Pacientes</span>
            </a>
            <ul class="sub">
                @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("Reportes"))
                {
                    <li>@Html.ActionLink("Gestion de Pacientes", "Index", "Paciente")</li>
                    <li>@Html.ActionLink("Gestion de Reportes", "Reportes", "Paciente")</li>
                }
            </ul>
        </li>

    </ul>
    <!-- sidebar menu end-->
</div>

SeguridadWebv2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Consultorio Virtual", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class ="active">@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li class="active">@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="active">@Html.ActionLink("Dashboard", "Dashboard", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container indexcontainer">
        @RenderBody()
        <hr />
        <footer>
            <p>Consultorio Virtual - &copy; @DateTime.Now.Year</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SeguridadWebv2/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/adminPanel")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <section id="container">
        <div class="navbar navbar-fixed-top">
            <header class="header black-bg">
                @Html.ActionLink("Consultorio Virtual", "Index", "Home", null, new { @class = "navbar-brand" })
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Dashboard", "Dashboard", "Home")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </header>
        </div>
            <!--sidebar start-->
            <aside>
                @Html.Partial("_DashboardIzquierdo")
            </aside>
            <!--sidebar end-->


            <section id="main-content">
                <section class="wrapper">
                    @RenderBody()
                </section>
            </section>
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
</section>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/adminPanelJs")
        @RenderSection("scripts", required: false)
</body>
</html>

SeguridadWebv2/Views/Shared/_LayoutEspecialista.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    @Styles.Render("~/Content/cssespecialista")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript">CRISP_WEBSITE_ID = "55779855-011d-4335-b4c4-94cc7524fb14";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.im/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Consultorio Virtual", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li class="active">@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li class="active">@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="active">@Html.ActionLink("Dashboard", "Dashboard", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container indexcontainer">
        @RenderBody()
        <hr />
        <footer>
            <p>Consultorio Virtual - &copy; @DateTime.Now.Year</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SeguridadWebv2/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    @Styles.Render("~/Content/csshome")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript">CRISP_WEBSITE_ID = "55779855-011d-4335-b4c4-94cc7524fb14"; (function () { d = document; s = d.createElement("script"); s.src = "https://client.crisp.im/l.js"; s.async = 1; d.getElementsByTagName("head")[0].appendChild(s); })();</script>
</head>
<body id="page-top">
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                @Html.ActionLink("Consultorio Virtual", "Index", "Home", null, new { @class = "navbar-brand page-scroll" })
            </div>
            <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li class="active">@Html.ActionLink("Dashboard", "Dashboard", "Home")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            @Html.Partial("_HeaderBusqueda")
        </div>
    </header>

    <div>
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/script-custom")
    @RenderSection("scripts", required: false)

</body>
</html>

SeguridadWebv2/Views/Shared/_LayoutVideoConf.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    @Styles.Render("~/Content/VideoConf")
</head>
<body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Consultorio Virtual", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
                        <li class="active">@Html.ActionLink("Acerca de", "About", "Home")</li>
                        <li class="active">@Html.ActionLink("Contacto", "Contact", "Home")</li>
                        @if (Request.IsAuthenticated)
                        {
                            <li class="active">@Html.ActionLink("Dashboard", "Dashboard", "Home")</li>
                        }
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/VideoConfJs")

    @RenderSection("scripts", required: false)
</body>
</html>