SeguridadWebv2/Controllers/AccionesAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using SeguridadWebv2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SeguridadWebv2.Controllers
{
    [Authorize(Roles = "Admin, AllPermisos")]
    public class AccionesAdminController : Controller
    {
        public AccionesAdminController()
        {
        }

        public AccionesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Detalles(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Agregar()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Agregar(AccionViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new ApplicationRole(roleViewModel.Name);
                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Editar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            AccionViewModel roleModel = new AccionViewModel { Id = role.Id, Name = role.Name };
            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Editar([Bind(Include = "Name,Id")] AccionViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;
                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Eliminar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Eliminar")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmarEliminar(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

SeguridadWebv2/Views/AccionesAdmin/Agregar.cshtml
@model SeguridadWebv2.Models.AccionViewModel
@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Agregar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Agregar un nuevo Permiso/Accion.</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="control-label col-md-2">
                Nombre de la Acción / Permiso
            </div>
            <div class="col-md-6 input-group">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                <span class="input-group-addon">
                    <span class="fa fa-check-circle-o">
                    </span>
                </span>
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SeguridadWebv2/Views/AccionesAdmin/Detalles.cshtml
@model SeguridadWebv2.Models.ApplicationRole
@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Detalles</h2>
<div>
    <h4>Roles.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<h4>List of users in this role</h4>
@if (ViewBag.UserCount == 0)
{
    <hr />
    <p>No users found in this role.</p>
}
<table class="table">
    @foreach (var item in ViewBag.Users)
    {
        <tr>
            <td>
                @item.UserName
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SeguridadWebv2/Views/AccionesAdmin/Editar.cshtml
@model SeguridadWebv2.Models.AccionViewModel
@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Editar</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Formulario Editar Acciones / Permisos.</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="control-label col-md-2">
                Nombre de la Acción / Permiso
            </div>
            <div class="col-md-6 input-group">
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                <span class="input-group-addon">
                    <span class="fa fa-check-circle-o">
                    </span>
                </span>
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SeguridadWebv2/Views/AccionesAdmin/Eliminar.cshtml
@model SeguridadWebv2.Models.ApplicationRole
@{
    ViewBag.Title = "Eliminar";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this Role? </h3>
<p>Deleting this Role will remove all users from this role. It will not delete the users.</p>
<div>
    <h4>Role.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SeguridadWebv2/Views/AccionesAdmin/Index.cshtml
@model IEnumerable<SeguridadWebv2.Models.ApplicationRole>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Listado de Permisos / Acciones</h2>
<p>
    @if (User.IsInRole("Admin") || User.IsInRole("Agregar_Permiso")) {
        @Html.ActionLink("Agregar Permiso/Acción", "Agregar")
    }
</p>
<div class="row">
    <table class="table table-striped table-condensed">
        <thead>
        <tr>
            <th>Nombre Acción/Permiso</th>
            <th>
            </th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td class="text-center">
                    @if (User.IsInRole("Admin") || User.IsInRole("Detalles_Permiso")) {
                    <a href="@Url.Action("Detalles", "AccionesAdmin", new { id = item.Id })" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-pencil"></span> Detalle</a>}
                    @if (User.IsInRole("Admin") || User.IsInRole("Editar_Permiso")) {
                    <a href="@Url.Action("Editar", "AccionesAdmin", new { id = item.Id })" class='btn btn-info btn-xs'><span class="glyphicon glyphicon-edit"></span> Editar</a>}                                                                                                                                                       
                    @if (User.IsInRole("Admin") || User.IsInRole("Eliminar_Permiso")) {
                    <a href="@Url.Action("Eliminar", "AccionesAdmin", new { id = item.Id })" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Eliminar</a>}
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>