SeguridadWebv2/Models/Aplicacion/Horario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SeguridadWebv2.Models.Aplicacion
{
    public class Horario
    {
        public Horario()
        {
            this.IDHorario = Guid.NewGuid().ToString();
            this.HorariosDisponibles = new List<HorarioDisponible>();
        }

        [Key]
        public string IDHorario { get; set; }
        public int Duracion { get; set; }
        public EstadoHorario Estado { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        [DataType(DataType.Time)]
        public DateTime HoraInicio { get; set; }
        public int CantidadTurnos { get; set; }
        public string EspecialistaId { get; set; }

        [ForeignKey("EspecialistaId")]
        public virtual Especialista Especialista { get; set; }
        public DiasDelaSemana Dia { get; set; }
        public MesDelAno Mes { get; set; }
        public virtual List<HorarioDisponible> HorariosDisponibles { get; set; }
    }

    public enum EstadoHorario
    {
        Disponible = 1,
        Ocupado = 2,
        Pendiente = 3
    }
    
    public enum DiasDelaSemana
    {
        Domingo = 0,
        Lunes = 1,
        Martes = 2,
        Miercoles = 3,
        Jueves = 4,
        Viernes = 5,
        Sabado = 6
    }

    public enum MesDelAno
    {
        Enero = 1,
        Febrero = 2,
        Marzo = 3,
        Abril = 4,
        Mayo = 5,
        Junio = 6,
        Julio = 7,
        Agosto = 8,
        Septiembre = 9,
        Octubre = 10,
        Noviembre = 11,
        Diciembre = 12
    }
}

SeguridadWebv2/Models/ViewModels/HorarioViewModel.cs
using SeguridadWebv2.Models.Aplicacion;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SeguridadWebv2.Models.ViewModels
{
    public class HorarioViewModel
    {
        public HorarioViewModel()
        {
            this.HorariosDisponibles = new List<HorarioDisponible>();
        }

        public string IDHorario { get; set; }
        public int Duracion { get; set; }
        public EstadoHorario Estado { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh:mm tt}")]
        [DataType(DataType.Time)]
        public DateTime HoraInicio { get; set; }
        public int CantidadTurnos { get; set; }
        public DiasDelaSemana Dia { get; set; }
        public MesDelAno Mes { get; set; }
        public Especialista Especialista { get; set; }
        public List<HorarioDisponible> HorariosDisponibles { get; set; }
        public string EspecialistaID { get; set; }

        public string FullNombreEspecialista
        {
            get
            {
                return this.Especialista.Nombre + " " + this.Especialista.Apellido;
            }
        }
    }
}

SeguridadWebv2/Controllers/HorarioController.cs
using SeguridadWebv2.Models;
using SeguridadWebv2.Models.Aplicacion;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SeguridadWebv2.Models.ViewModels;

namespace SeguridadWebv2.Controllers
{
    public class HorarioController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Horario
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var horarios = db.Horarios.Include("Especialista").Include("HorariosDisponibles").ToList();
            
            IEnumerable<HorarioViewModel> _horariosvm = horarios.Select(b => new HorarioViewModel
            {
                IDHorario = b.IDHorario,
                Especialista = b.Especialista,
                CantidadTurnos = b.CantidadTurnos,
                Dia = b.Dia,
                Duracion = b.Duracion,
                Estado = b.Estado,
                HoraInicio = b.HoraInicio,
                HorariosDisponibles = b.HorariosDisponibles.ToList(),
                Mes = b.Mes
            })
            .ToList();
            return View(_horariosvm.ToList());
        }
        
        [HttpGet]
        [Authorize(Roles = "Profesionales, Detalle_Horario, Profesional")]
        public ActionResult MisHorarios()
        {
            var EspecialistaID = User.Identity.GetUserId();

            if (EspecialistaID == null)
            {
                return HttpNotFound();
            }

            var horarios = db.Horarios.Include("Especialista").Include("HorariosDisponibles").Where(x => x.EspecialistaId == EspecialistaID).ToList();

            IEnumerable<HorarioViewModel> _horariosvm = horarios.Select(b => new HorarioViewModel
            {
                IDHorario = b.IDHorario,
                Especialista = b.Especialista,
                CantidadTurnos = b.CantidadTurnos,
                Dia = b.Dia,
                Duracion = b.Duracion,
                Estado = b.Estado,
                HoraInicio = b.HoraInicio,
                HorariosDisponibles = b.HorariosDisponibles.ToList(),
                Mes = b.Mes
            })
            .ToList();
            return View(_horariosvm.ToList());
        }

        [HttpGet]
        [Authorize(Roles = "Admin, Profesionales, Detalle_Horario, Profesional")]
        public ActionResult Detalle(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horarioModels = db.Horarios.Include(i => i.Especialista)
                                  .Include(i => i.HorariosDisponibles)
                                  .SingleOrDefault(x => x.IDHorario == id);

            if (horarioModels == null)
            {
                return HttpNotFound();
            }

            HorarioViewModel _horariosvm = new HorarioViewModel
            {
                IDHorario = horarioModels.IDHorario,
                Especialista = horarioModels.Especialista,
                CantidadTurnos = horarioModels.CantidadTurnos,
                Dia = horarioModels.Dia,
                Duracion = horarioModels.Duracion,
                Estado = horarioModels.Estado,
                HoraInicio = horarioModels.HoraInicio,
                HorariosDisponibles = horarioModels.HorariosDisponibles.OrderBy(x => x.Dia.Date).ToList(),
                Mes = horarioModels.Mes
            };
            
            return View(_horariosvm);
        }

        // GET: Horario/Create
        [HttpGet]
        [Authorize(Roles = "Admin, Profesionales, Agregar_Horario, Profesional")]
        public ActionResult Create()
        {
            var horarioModel = new HorarioViewModel();
            return View(horarioModel);
        }

        // POST: Horario/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Duracion,HoraInicio,CantidadTurnos,Mes,Dia")] HorarioViewModel horarioModels)
        {
            if (ModelState.IsValid)
            {
                //db.Horarios.Add(horarioModels);
                //db.SaveChanges();
                horarioModels.EspecialistaID = User.Identity.GetUserId();
                horarioModels.Estado = EstadoHorario.Disponible;
                //Especialista usuario = db.Especialistas.Where(x => x.Id.Contains(horarioModels.EspecialistaID)).FirstOrDefault();
                List<DateTime> lstSundays = new List<DateTime>();

                int intYear = DateTime.Now.Year;
                int intDaysThisMonth = DateTime.DaysInMonth(intYear, (int)horarioModels.Mes /*intMonth*/);
                DateTime oBeginnngOfThisMonth = new DateTime(intYear, (int)horarioModels.Mes/*intMonth*/, 1);
                for (int i = 1; i < intDaysThisMonth + 1; i++)
                {
                    if (oBeginnngOfThisMonth.AddDays(i - 1).DayOfWeek == (DayOfWeek)Convert.ToInt32(horarioModels.Dia))
                    {
                        lstSundays.Add(new DateTime(intYear, (int)horarioModels.Mes/*intMonth*/, i));
                    }
                }
                
                foreach (DateTime dia in lstSundays)
                {
                    int totalTurnos = horarioModels.CantidadTurnos;
                    DateTime ultimaHora = DateTime.Now;
                    while (totalTurnos != 0)
                    {
                        HorarioDisponible horarioDisponible = new HorarioDisponible();
                        horarioDisponible.Dia = dia;
                        horarioDisponible.HorarioId = horarioModels.IDHorario;
                        if (horarioModels.CantidadTurnos == totalTurnos)
                        {
                            horarioDisponible.HoraInicio = horarioModels.HoraInicio;
                            horarioDisponible.HoraFin = horarioDisponible.HoraInicio.AddMinutes(horarioModels.Duracion);
                            totalTurnos -= 1;
                            ultimaHora = horarioDisponible.HoraFin;
                        }
                        else
                        {
                            horarioDisponible.HoraInicio = ultimaHora;
                            horarioDisponible.HoraFin = horarioDisponible.HoraInicio.AddMinutes(horarioModels.Duracion);
                            totalTurnos -= 1;
                            ultimaHora = horarioDisponible.HoraFin;
                        }
                        horarioModels.HorariosDisponibles.Add(horarioDisponible);
                    }
                }

                var horario = new Horario
                {
                    Dia = horarioModels.Dia,
                    Duracion = horarioModels.Duracion,
                    HoraInicio = horarioModels.HoraInicio,
                    Estado = horarioModels.Estado,
                    Mes = horarioModels.Mes,
                    HorariosDisponibles = horarioModels.HorariosDisponibles,
                    CantidadTurnos = horarioModels.CantidadTurnos,
                    EspecialistaId = horarioModels.EspecialistaID
                };

                db.Horarios.Add(horario);
                db.SaveChanges();
            }
            return View("Dashboard", "Home");
        }

        // GET: Horario/Edit/5
        [HttpGet]
        [Authorize(Roles = "Admin, Profesionales, Editar_Horario, Profesional")]
        public ActionResult Editar(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horarioModels = db.Horarios.Find(id);
            if (horarioModels == null)
            {
                return HttpNotFound();
            }
            return View(horarioModels);
        }

        // POST: Horario/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "Id,Duracion,HoraInicio,CantidadTurnos,EspecialistaID")] Horario horarioModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(horarioModels).State = EntityState.Modified;
                db.SaveChanges();
                return View("Dashboard", "Home");
            }
            return View(horarioModels);
        }

        // GET: Horario/Delete/5
        [HttpGet]
        [Authorize(Roles = "Admin, Profesionales, Eliminar_Horario, Profesional")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Horario horarioModels = db.Horarios.Find(id);
            if (horarioModels == null)
            {
                return HttpNotFound();
            }
            return View(horarioModels);
        }

        // POST: Horario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Horario horarioModels = db.Horarios.Find(id);
            db.Horarios.Remove(horarioModels);
            db.SaveChanges();
            return View("Dashboard", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        [HttpGet]
        public ActionResult ListHorarioDisponibles(int? id)

SeguridadWebv2/Views/Horario/Create.cshtml
@model SeguridadWebv2.Models.ViewModels.HorarioViewModel
@{
    ViewBag.Title = "Agregar Horario";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}
<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Horario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HoraInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @*@Html.TextBoxFor(model => model.HoraInicio , new { @class = "dp datepicker", Value = DateTime. })*@
                @*@string.Format("{0: hh:mm}", Convert.ToDateTime(Html.DisplayFor(model => model.HoraInicio).ToString()))*@
                @*@Html.EditorFor(model => model.HoraInicio, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.EditorFor(model => model.HoraInicio)

                @Html.ValidationMessageFor(model => model.HoraInicio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CantidadTurnos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.CantidadTurnos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantidadTurnos, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Dia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.DropDownListFor(model => model.Dia, new SelectList(Enum.GetValues(typeof(SeguridadWebv2.Models.Aplicacion.DiasDelaSemana))))
                @*@Html.EditorFor(model => model.Dia, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Dia, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
           @Html.LabelFor(model => model.Mes, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            @Html.DropDownListFor(model => model.Mes, new SelectList(Enum.GetValues(typeof(SeguridadWebv2.Models.Aplicacion.MesDelAno))))
            @*@Html.EditorFor(model => model.Dia, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Mes, "", new { @class = "text-danger" })
        </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SeguridadWebv2/Views/Horario/Detalle.cshtml
@model SeguridadWebv2.Models.ViewModels.HorarioViewModel
@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}

<h2>Detalles Horario</h2>
<div>
    <h4>Detalles del Horario.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CantidadTurnos)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CantidadTurnos)
        </dd>
    </dl>
</div>


@if (Model.Especialista != null)
{
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="well well-sm">
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <img src="@Url.Content(Model.Especialista.ImagenMedico)" alt="" class="img-rounded img-responsive" />
                </div>
                <div class="col-sm-6 col-md-8">
                    <h4>
                        @Html.DisplayFor(model => Model.FullNombreEspecialista)
                    </h4>
                    <small>
                        <cite title="Rosario, ARG">
                            Rosario, ARG <i class="glyphicon glyphicon-map-marker">
                            </i>
                        </cite>
                    </small>
                    <p>
                        <i class="glyphicon glyphicon-envelope"></i>@Html.DisplayFor(model => Model.Especialista.PhoneNumber)
                        <br />
                        <i class="glyphicon glyphicon-gift"></i>@Html.DisplayFor(model => Model.Especialista.UserName)
                    </p>
                </div>
            </div>
        </div>
    </div>
}

@if (Model.HorariosDisponibles.Count() > 0)
{
    <div class="row">
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>Día</th>
                    <th>Hora Inicio</th>
                    <th>Hora Fin</th>
                    <th>Precio</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.HorariosDisponibles)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Dia)</td>
                        <td>@Html.DisplayFor(modelItem => item.HoraInicio)</td>
                        <td>@Html.DisplayFor(modelItem => item.HoraFin)</td>
                        <td>@Html.DisplayFor(modelItem => item.Precio)</td>
                        <td>@Html.DisplayFor(modelItem => item.Disponible)</td>
                        <td class="text-center">
                            @if (User.IsInRole("Admin") || User.IsInRole("Detalle_HorarioDisponible") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Detalle", "Horario", new { id = item.Id })" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-pencil"></span> Detalle</a>}
                            @if (User.IsInRole("Admin") || User.IsInRole("Editar_HorarioDisponible") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Editar", "Horario", new { id = item.Id })" class='btn btn-info btn-xs'><span class="glyphicon glyphicon-edit"></span> Editar</a>}
                            @if (User.IsInRole("Admin") || User.IsInRole("Eliminar_HorarioDisponible") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Eliminar", "Horario", new { id = item.Id })" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Eliminar</a>}
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div>No se encontraron Horarios Asignados</div>
}

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDHorario }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SeguridadWebv2/Views/Horario/Editar.cshtml
@model SeguridadWebv2.Models.ViewModels.HorarioViewModel
@{
    ViewBag.Title = "Editar Horario";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editar Horario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDHorario)
        <div class="form-group">
            @Html.LabelFor(model => model.Duracion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Duracion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duracion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HoraInicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.HoraInicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraInicio, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CantidadTurnos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.CantidadTurnos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantidadTurnos, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SeguridadWebv2/Views/Horario/Index.cshtml
@model IEnumerable<SeguridadWebv2.Models.ViewModels.HorarioViewModel>

@{
    ViewBag.Title = "Listado de Horario";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}
<h2>Listado de Horarios</h2>
<p>
    @Html.ActionLink("Agregar Horario", "Create")
</p>
@if (Model.Count() > 0)
{
<div class="row">
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>Especialista</th>
                <th>Duración</th>
                <th>Hora Inicio</th>
                <th>Cantidad Turnos</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.FullNombreEspecialista)</td>
                <td>@Html.DisplayFor(modelItem => item.Duracion)</td>
                <td>@Html.DisplayFor(modelItem => item.HoraInicio)</td>
                <td>@Html.DisplayFor(modelItem => item.CantidadTurnos)</td>
                <td class="text-center">
                    @if (User.IsInRole("Admin") || User.IsInRole("Detalle_Horario") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Detalle", "Horario", new { id = item.IDHorario })" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-pencil"></span> Detalle</a>}
                    @if (User.IsInRole("Admin") || User.IsInRole("Editar_Horario") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Editar", "Horario", new { id = item.IDHorario })" class='btn btn-info btn-xs'><span class="glyphicon glyphicon-edit"></span> Editar</a>}
                    @if (User.IsInRole("Admin") || User.IsInRole("Eliminar_Horario") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Eliminar", "Horario", new { id = item.IDHorario })" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Eliminar</a>}
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>
} else {
    <div>No se encontraron Horarios Asignados</div>
}

SeguridadWebv2/Views/Horario/MisHorarios.cshtml
@model IEnumerable<SeguridadWebv2.Models.ViewModels.HorarioViewModel>

@{
    ViewBag.Title = "Listado de Horario";
    Layout = "~/Views/Shared/_LayoutDashboard.cshtml";
}
<h2>Listado de Horarios</h2>
<p>
    @Html.ActionLink("Agregar Horario", "Create")
</p>
@if (Model.Count() > 0)
{
    <div class="row">
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>Especialista</th>
                    <th>Duración</th>
                    <th>Hora Inicio</th>
                    <th>Cantidad Turnos</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.FullNombreEspecialista)</td>
                        <td>@Html.DisplayFor(modelItem => item.Duracion)</td>
                        <td>@Html.DisplayFor(modelItem => item.HoraInicio)</td>
                        <td>@Html.DisplayFor(modelItem => item.CantidadTurnos)</td>
                        <td class="text-center">
                            @if (User.IsInRole("Admin") || User.IsInRole("Detalle_Horario") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Detalle", "Horario", new { id = item.IDHorario })" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-pencil"></span> Detalle</a>}
                            @if (User.IsInRole("Admin") || User.IsInRole("Editar_Horario") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Editar", "Horario", new { id = item.IDHorario })" class='btn btn-info btn-xs'><span class="glyphicon glyphicon-edit"></span> Editar</a>}
                            @if (User.IsInRole("Admin") || User.IsInRole("Eliminar_Horario") || User.IsInRole("Profesionales"))
                    {<a href="@Url.Action("Eliminar", "Horario", new { id = item.IDHorario })" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Eliminar</a>}
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div>No se encontraron Horarios Asignados</div>
}

SeguridadWebv2/Views/Horario/_ListHorarioDisponibles.cshtml
@model IEnumerable<SeguridadWebv2.Models.Aplicacion.HorarioDisponible>
@{
    ViewBag.Title = "Index";
}
<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Dia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraInicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HoraFin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Disponible)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Dia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraFin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disponible)
            </td>

        </tr>
    }
</table>